version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: sigai-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  redis:
    image: redis:alpine
    container_name: sigai-cache
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: sigai-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sigai_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend-node
    container_name: sigai-backend
    depends_on:
      - mosquitto
      - redis
      - postgres
    environment:
      - MQTT_HOST=mosquitto
      - REDIS_HOST=redis
      - DB_HOST=postgres
    ports:
      - "3000:3000" # API y WebSockets